# Generated by Django 5.0.4 on 2024-06-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='minigame/bosses/')),
                ('health', models.IntegerField(default=100)),
                ('health_regen', models.IntegerField(default=100)),
                ('duration', models.IntegerField(default=120)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('guide', models.TextField(blank=True, null=True)),
                ('reward', models.IntegerField(default=100)),
                ('defeat_penalty', models.IntegerField(default=10)),
            ],
        ),
    ]
