# Generated by Django 5.0.4 on 2024-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0002_alter_boss_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boss',
            name='image',
            field=models.ImageField(upload_to='minigame/bosses/'),
        ),
    ]
