# Generated by Django 5.0.4 on 2024-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0003_alter_boss_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='defeat_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boss',
            name='victory_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
