# Generated by Django 5.0.4 on 2024-06-24 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0008_rename_user_fight_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fight',
            options={'verbose_name': 'Fight', 'verbose_name_plural': 'Fights'},
        ),
        migrations.AlterField(
            model_name='fight',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minigame.boss'),
        ),
    ]
