# Generated by Django 5.0.4 on 2024-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0010_remove_fight_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='fight_done',
            field=models.BooleanField(default=False),
        ),
    ]
