# Generated by Django 5.0.4 on 2024-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0011_fight_fight_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='health_regen',
            field=models.IntegerField(default=0),
        ),
    ]
