# Generated by Django 5.0.4 on 2024-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0012_fight_health_regen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='max_health',
            field=models.IntegerField(default=0),
        ),
    ]
