# Generated by Django 5.0.4 on 2024-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigame', '0013_fight_max_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='attack_damage',
            field=models.IntegerField(default=0),
        ),
    ]
