# Generated by Django 5.0.4 on 2024-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_bonus_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
