# Generated by Django 5.0.4 on 2024-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='boss',
            field=models.IntegerField(default=0),
        ),
    ]
