# Generated by Django 5.0.4 on 2024-06-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_boss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='boss',
            field=models.IntegerField(default=1),
        ),
    ]
