# Generated by Django 5.0.5 on 2024-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0004_pokemon_price'),
        ('users', '0007_alter_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pokemons',
            field=models.ManyToManyField(blank=True, to='pokemons.pokemon'),
        ),
    ]
