# Generated by Django 5.0.4 on 2024-05-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_userachievement_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentactivity',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='RecentActivity',
        ),
    ]
