# Generated by Django 5.0.4 on 2024-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_status',
            field=models.IntegerField(default=0),
        ),
    ]
