# Generated by Django 5.0.4 on 2024-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.CharField(max_length=255)),
                ('against_bug', models.FloatField()),
                ('against_dark', models.FloatField()),
                ('against_dragon', models.FloatField()),
                ('against_electric', models.FloatField()),
                ('against_fairy', models.FloatField()),
                ('against_fight', models.FloatField()),
                ('against_fire', models.FloatField()),
                ('against_flying', models.FloatField()),
                ('against_ghost', models.FloatField()),
                ('against_grass', models.FloatField()),
                ('against_ground', models.FloatField()),
                ('against_ice', models.FloatField()),
                ('against_normal', models.FloatField()),
                ('against_poison', models.FloatField()),
                ('against_psychic', models.FloatField()),
                ('against_rock', models.FloatField()),
                ('against_steel', models.FloatField()),
                ('against_water', models.FloatField()),
                ('attack', models.IntegerField()),
                ('base_egg_steps', models.IntegerField()),
                ('base_happiness', models.IntegerField()),
                ('base_total', models.IntegerField()),
                ('capture_rate', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=100)),
                ('defense', models.IntegerField()),
                ('experience_growth', models.CharField(max_length=50)),
                ('height', models.FloatField()),
                ('hp', models.IntegerField()),
                ('japanese_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('percentage_male', models.FloatField(null=True)),
                ('pokedex_number', models.IntegerField(unique=True)),
                ('sp_attack', models.IntegerField()),
                ('sp_defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('type1', models.CharField(max_length=50)),
                ('type2', models.CharField(max_length=50, null=True)),
                ('weight', models.FloatField()),
                ('generation', models.IntegerField()),
                ('is_legendary', models.BooleanField()),
            ],
        ),
    ]
