# Generated by Django 5.0.4 on 2024-04-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_alter_pokemon_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
