# Generated by Django 5.0.5 on 2024-05-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0003_alter_pokemon_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
