# Generated by Django 5.0.4 on 2024-06-29 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokemons', '0005_alter_pokemon_attack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemons_received', models.ManyToManyField(related_name='received_trades', to='pokemons.pokemon')),
                ('pokemons_send', models.ManyToManyField(related_name='sent_trades', to='pokemons.pokemon')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
